services:
  nw-mysql-db:
    image: mysql:8.0
    environment:
      - 'MYSQL_ROOT_PASSWORD=test12345'
      - 'MYSQL_USER=nw'
      - 'MYSQL_PASSWORD=test12345'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - nw-network

networks:
  nw-network:
    driver: bridge
 