CREATE DATABASE nw;

CREATE TABLE nw.post (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL
);

CREATE TABLE nw.comment (
  id INT PRIMARY KEY AUTO_INCREMENT,
  post_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE RESTRICT
);